<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArticlesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('articles')->insert([
            ['code' => 'IEA', 'base_value' => 4000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'PMATR.', 'base_value' => 15000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'CONF.', 'base_value' => 13000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'PROPBIO', 'base_value' => 27000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'PROPSOC', 'base_value' => 27000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'PROPPED', 'base_value' => 27000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'PROPGEO', 'base_value' => 25000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'PROPHIST', 'base_value' => 25000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'PROPPSG', 'base_value' => 25000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'PROPRI', 'base_value' => 25000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'PROPDIR', 'base_value' => 25000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'PROPGRH', 'base_value' => 25000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'PROPPSJ', 'base_value' => 25000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'PROPTEC', 'base_value' => 28000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'PROPEDF', 'base_value' => 28000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'PROPCEE', 'base_value' => 25000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'PROPECO', 'base_value' => 25000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'PROPCOA', 'base_value' => 27000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'PROPGEE', 'base_value' => 27000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'AM', 'base_value' => 8000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'C', 'base_value' => 25000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'DN', 'base_value' => 12000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'DNU', 'base_value' => 15000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'DF', 'base_value' => 5000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'DFU', 'base_value' => 7000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'DSN', 'base_value' => 9000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'DSNU', 'base_value' => 10000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'DL', 'base_value' => 15000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'DECSADEFC', 'base_value' => 15000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'DECSADFCT', 'base_value' => 7500, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'D', 'base_value' => 20000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'EM', 'base_value' => 3000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'EXE', 'base_value' => 7500, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'MN', 'base_value' => 6000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'EXR', 'base_value' => 7500, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'F', 'base_value' => 50, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'REC', 'base_value' => 6000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'INTC', 'base_value' => 8000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'MC', 'base_value' => 10000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'PEDEQUIV', 'base_value' => 2500, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'PEDTR', 'base_value' => 20000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'IPEXCA', 'base_value' => 6000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'IPFCA', 'base_value' => 6000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'CATRFC', 'base_value' => 12000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'IFER', 'base_value' => 0, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'RP', 'base_value' => 10000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'PJCE', 'base_value' => 2000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'PJCP', 'base_value' => 5000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'MCE', 'base_value' => 3000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'MCP', 'base_value' => 5000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'CAEST', 'base_value' => 500, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['code' => 'TFC', 'base_value' => 150000, 'created_by' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);

        DB::table('article_translations')->insert([
            ['article_id' => 1, 'language_id' => 1, 'display_name' => 'INSCRIÇÃO AO EXAME DE ACESSO', 'description' => 'INSCRIÇÃO AO EXAME DE ACESSO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 2, 'language_id' => 1, 'display_name' => 'PRÉ-MATRICULA', 'description' => 'PRÉ-MATRICULA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 3, 'language_id' => 1, 'display_name' => 'CONFIRMAÇÃO DE MATRÍCULA', 'description' => 'CONFIRMAÇÃO DE MATRÍCULA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 4, 'language_id' => 1, 'display_name' => 'PROPINA MENSAL CURSO L. EM BIOLOGIA', 'description' => 'PROPINA MENSAL CURSO L. EM BIOLOGIA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 5, 'language_id' => 1, 'display_name' => 'PROPINA MENSAL CURSO L. EM SOCIOLOGIA', 'description' => 'PROPINA MENSAL CURSO L. EM SOCIOLOGIA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 6, 'language_id' => 1, 'display_name' => 'PROPINA MENSAL CURSO L. EM PEDAGOGIA', 'description' => 'PROPINA MENSAL CURSO L. EM PEDAGOGIA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 7, 'language_id' => 1, 'display_name' => 'PROPINA MENSAL CURSO L. EM GEOGRAFIA', 'description' => 'PROPINA MENSAL CURSO L. EM GEOGRAFIA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 8, 'language_id' => 1, 'display_name' => 'PROPINA MENSAL CURSO L. EM HISTÓRIA', 'description' => 'PROPINA MENSAL CURSO L. EM HISTÓRIA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 9, 'language_id' => 1, 'display_name' => 'PROPINA MENSAL CURSO L. EM PSICOLOGIA', 'description' => 'PROPINA MENSAL CURSO L. EM PSICOLOGIA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 10, 'language_id' => 1, 'display_name' => 'PROPINA MENSAL CURSO L. EM RELAÇÕES INTERNACIONAIS', 'description' => 'PROPINA MENSAL CURSO L. EM RELAÇÕES INTERNACIONAIS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 11, 'language_id' => 1, 'display_name' => 'PROPINA MENSAL DO CURSO DE L. EM DIREITO', 'description' => 'PROPINA MENSAL DO CURSO DE L. EM DIREITO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 12, 'language_id' => 1, 'display_name' => 'PROPINA MENSAL DO CURSO DE L. EM G.R.H.', 'description' => 'PROPINA MENSAL DO CURSO DE L. EM G.R.H.', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 13, 'language_id' => 1, 'display_name' => 'PROPINA MENSAL DO CURSO DE L. EM PS. JURÍDICA', 'description' => 'PROPINA MENSAL DO CURSO DE L. EM PS. JURÍDICA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 14, 'language_id' => 1, 'display_name' => 'PROPTEC PROPINA MENSAL DE L. EM ENGa INFORMÁTICA', 'description' => 'PROPTEC PROPINA MENSAL DE L. EM ENGa INFORMÁTICA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 15, 'language_id' => 1, 'display_name' => 'PROPINA MENSAL DE L. EM DESP. ED. FÍSICA', 'description' => 'PROPINA MENSAL DE L. EM DESP. ED. FÍSICA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 16, 'language_id' => 1, 'display_name' => 'PROPINA MENSAL CIÊNCIAS ECONÓMICAS EMPRESARIAIS', 'description' => 'PROPINA MENSAL CIÊNCIAS ECONÓMICAS EMPRESARIAIS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 17, 'language_id' => 1, 'display_name' => 'PROPINA MENSAL CIÊNCIAS ECONÓMICAS EMPRESARIAIS - ECONOMIA', 'description' => 'PROPINA MENSAL CIÊNCIAS ECONÓMICAS EMPRESARIAIS - ECONOMIA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 18, 'language_id' => 1, 'display_name' => 'PROPINA MENSAL CIÊNCIAS ECONÓMICAS EMPRESARIAIS - CONTABILIDADE E AUDITORIA', 'description' => 'PROPINA MENSAL CIÊNCIAS ECONÓMICAS EMPRESARIAIS - CONTABILIDADE E AUDITORIA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 19, 'language_id' => 1, 'display_name' => 'PROPINA MENSAL CIÊNCIAS ECONÓMICAS EMPRESARIAIS - GESTÃO DE EMPRESAS', 'description' => 'PROPINA MENSAL CIÊNCIAS ECONÓMICAS EMPRESARIAIS - GESTÃO DE EMPRESAS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 20, 'language_id' => 1, 'display_name' => 'ANULAÇÃO DE MATRÍCULA', 'description' => 'ANULAÇÃO DE MATRÍCULA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 21, 'language_id' => 1, 'display_name' => 'CERTIFICADO', 'description' => 'CERTIFICADO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 22, 'language_id' => 1, 'display_name' => 'DECLARAÇÃO COM NOTAS', 'description' => 'DECLARAÇÃO COM NOTAS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 23, 'language_id' => 1, 'display_name' => 'DECLARAÇÃO COM NOTAS URGENTE', 'description' => 'DECLARAÇÃO COM NOTAS URGENTE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 24, 'language_id' => 1, 'display_name' => 'DECLARAÇÃO DE FREQUÊNCIA', 'description' => 'DECLARAÇÃO DE FREQUÊNCIA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 25, 'language_id' => 1, 'display_name' => 'DECLARAÇÃO DE FREQUÊNCIA URGENTE', 'description' => 'DECLARAÇÃO DE FREQUÊNCIA URGENTE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 26, 'language_id' => 1, 'display_name' => 'DECLARAÇÃO SEM NOTAS', 'description' => 'DECLARAÇÃO SEM NOTAS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 27, 'language_id' => 1, 'display_name' => 'DECLARAÇÃO SEM NOTAS URGENTE', 'description' => 'DECLARAÇÃO SEM NOTAS URGENTE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 28, 'language_id' => 1, 'display_name' => 'DECLARAÇÃO DE LICENCIATURA', 'description' => 'DECLARAÇÃO DE LICENCIATURA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 29, 'language_id' => 1, 'display_name' => 'DECORAÇÃO DA SALA PARA DEFESA DE FIM DE CURSO', 'description' => 'DECORAÇÃO DA SALA PARA DEFESA DE FIM DE CURSO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 30, 'language_id' => 1, 'display_name' => 'DECORAÇÃO DA SALA PARA DEFESA DE FIM DE CURSO POR TERCEIROS', 'description' => 'DECORAÇÃO DA SALA PARA DEFESA DE FIM DE CURSO POR TERCEIROS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 31, 'language_id' => 1, 'display_name' => 'DIPLOMA', 'description' => 'DIPLOMA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 32, 'language_id' => 1, 'display_name' => 'EMISSÃO DE CARTÃO DE ESTUDANTE', 'description' => 'EMISSÃO DE CARTÃO DE ESTUDANTE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 33, 'language_id' => 1, 'display_name' => 'EXAME EXTRAORDINÁRIO', 'description' => 'EXAME EXTRAORDINÁRIO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 34, 'language_id' => 1, 'display_name' => 'MELHORIA DE NOTAS', 'description' => 'MELHORIA DE NOTAS', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 35, 'language_id' => 1, 'display_name' => 'EXAME DE RECUPERAÇÃO', 'description' => 'EXAME DE RECUPERAÇÃO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 36, 'language_id' => 1, 'display_name' => 'FOLHA DE PROVA', 'description' => 'FOLHA DE PROVA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 37, 'language_id' => 1, 'display_name' => 'INSCRIÇÃO AO EXAME DE RECURSO', 'description' => 'INSCRIÇÃO AO EXAME DE RECURSO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 38, 'language_id' => 1, 'display_name' => 'INTEGRAÇÃO CURRICULAR', 'description' => 'INTEGRAÇÃO CURRICULAR', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 39, 'language_id' => 1, 'display_name' => 'MUDANÇA DE CURSO', 'description' => 'MUDANÇA DE CURSO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 40, 'language_id' => 1, 'display_name' => 'PEDIDO DE EQUIVALÊNCIA POR DISCIPLINA', 'description' => 'PEDIDO DE EQUIVALÊNCIA POR DISCIPLINA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 41, 'language_id' => 1, 'display_name' => 'PEDIDO DE TRANSFERÊNCIA', 'description' => 'PEDIDO DE TRANSFERÊNCIA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 42, 'language_id' => 1, 'display_name' => 'INSCRIÇÃO POR EXAME CADEIRA EM ATRASO', 'description' => 'INSCRIÇÃO POR EXAME CADEIRA EM ATRASO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 43, 'language_id' => 1, 'display_name' => 'INSCRIÇÃO POR FREQUÊNCIA CADEIRA EM ATRASO', 'description' => 'INSCRIÇÃO POR FREQUÊNCIA CADEIRA EM ATRASO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 44, 'language_id' => 1, 'display_name' => 'CADEIRA EM ATRASO DE FIM-DE-CURSO (apartir de Julho)', 'description' => 'CADEIRA EM ATRASO DE FIM-DE-CURSO (apartir de Julho)', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 45, 'language_id' => 1, 'display_name' => 'INSCRIÇÃO POR FREQUÊNCIA ESTUDANTE REPITENTE', 'description' => 'INSCRIÇÃO POR FREQUÊNCIA ESTUDANTE REPITENTE', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 46, 'language_id' => 1, 'display_name' => 'REVISÃO DE PROVA', 'description' => 'REVISÃO DE PROVA', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 47, 'language_id' => 1, 'display_name' => 'PARTICIPAÇÃO EM JORNADAS CIENTÍFICAS - ESTUDANTES', 'description' => 'PARTICIPAÇÃO EM JORNADAS CIENTÍFICAS - ESTUDANTES', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 48, 'language_id' => 1, 'display_name' => 'PARTICIPAÇÃO EM JORNADAS CIENTÍFICAS - DOCENTES', 'description' => 'PARTICIPAÇÃO EM JORNADAS CIENTÍFICAS - DOCENTES', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 49, 'language_id' => 1, 'display_name' => 'MINI-CURSOS / ESTUDANTES', 'description' => 'MINI-CURSOS / ESTUDANTES', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 50, 'language_id' => 1, 'display_name' => 'MINI-CURSOS / DOCENTES', 'description' => 'MINI-CURSOS / DOCENTES', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 51, 'language_id' => 1, 'display_name' => 'COTA ASSOCIAÇÃO DE ESTUDANTES - ANUAL', 'description' => 'COTA ASSOCIAÇÃO DE ESTUDANTES - ANUAL', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['article_id' => 52, 'language_id' => 1, 'display_name' => 'TRABALHO DE FIM DE CURSO', 'description' => 'TRABALHO DE FIM DE CURSO', 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);

        DB::table('article_extra_fees')->insert([
            ['article_id' => 2, 'fee_percent' => 0, 'max_delay_days' => 10],
            ['article_id' => 2, 'fee_percent' => 25, 'max_delay_days' => 30],
            ['article_id' => 3, 'fee_percent' => 0, 'max_delay_days' => 10],
            ['article_id' => 3, 'fee_percent' => 25, 'max_delay_days' => 30],
            ['article_id' => 4, 'fee_percent' => 0, 'max_delay_days' => 10],
            ['article_id' => 4, 'fee_percent' => 15, 'max_delay_days' => 15],
            ['article_id' => 4, 'fee_percent' => 30, 'max_delay_days' => 30],
            ['article_id' => 5, 'fee_percent' => 0, 'max_delay_days' => 10],
            ['article_id' => 5, 'fee_percent' => 15, 'max_delay_days' => 15],
            ['article_id' => 5, 'fee_percent' => 30, 'max_delay_days' => 30],
            ['article_id' => 6, 'fee_percent' => 0, 'max_delay_days' => 10],
            ['article_id' => 6, 'fee_percent' => 15, 'max_delay_days' => 15],
            ['article_id' => 6, 'fee_percent' => 30, 'max_delay_days' => 30],
            ['article_id' => 7, 'fee_percent' => 0, 'max_delay_days' => 10],
            ['article_id' => 7, 'fee_percent' => 15, 'max_delay_days' => 15],
            ['article_id' => 7, 'fee_percent' => 30, 'max_delay_days' => 30],
            ['article_id' => 8, 'fee_percent' => 0, 'max_delay_days' => 10],
            ['article_id' => 8, 'fee_percent' => 15, 'max_delay_days' => 15],
            ['article_id' => 8, 'fee_percent' => 30, 'max_delay_days' => 30],
            ['article_id' => 9, 'fee_percent' => 0, 'max_delay_days' => 10],
            ['article_id' => 9, 'fee_percent' => 15, 'max_delay_days' => 15],
            ['article_id' => 9, 'fee_percent' => 30, 'max_delay_days' => 30],
            ['article_id' => 10, 'fee_percent' => 0, 'max_delay_days' => 10],
            ['article_id' => 10, 'fee_percent' => 15, 'max_delay_days' => 15],
            ['article_id' => 10, 'fee_percent' => 30, 'max_delay_days' => 30],
            ['article_id' => 11, 'fee_percent' => 0, 'max_delay_days' => 10],
            ['article_id' => 11, 'fee_percent' => 15, 'max_delay_days' => 15],
            ['article_id' => 11, 'fee_percent' => 30, 'max_delay_days' => 30],
            ['article_id' => 12, 'fee_percent' => 0, 'max_delay_days' => 10],
            ['article_id' => 12, 'fee_percent' => 15, 'max_delay_days' => 15],
            ['article_id' => 12, 'fee_percent' => 30, 'max_delay_days' => 30],
            ['article_id' => 13, 'fee_percent' => 0, 'max_delay_days' => 10],
            ['article_id' => 13, 'fee_percent' => 15, 'max_delay_days' => 15],
            ['article_id' => 13, 'fee_percent' => 30, 'max_delay_days' => 30],
            ['article_id' => 14, 'fee_percent' => 0, 'max_delay_days' => 10],
            ['article_id' => 14, 'fee_percent' => 15, 'max_delay_days' => 15],
            ['article_id' => 14, 'fee_percent' => 30, 'max_delay_days' => 30],
            ['article_id' => 15, 'fee_percent' => 0, 'max_delay_days' => 10],
            ['article_id' => 15, 'fee_percent' => 15, 'max_delay_days' => 15],
            ['article_id' => 15, 'fee_percent' => 30, 'max_delay_days' => 30],
            ['article_id' => 16, 'fee_percent' => 0, 'max_delay_days' => 10],
            ['article_id' => 16, 'fee_percent' => 15, 'max_delay_days' => 15],
            ['article_id' => 16, 'fee_percent' => 30, 'max_delay_days' => 30],
            ['article_id' => 17, 'fee_percent' => 0, 'max_delay_days' => 10],
            ['article_id' => 17, 'fee_percent' => 15, 'max_delay_days' => 15],
            ['article_id' => 17, 'fee_percent' => 30, 'max_delay_days' => 30],
            ['article_id' => 18, 'fee_percent' => 0, 'max_delay_days' => 10],
            ['article_id' => 18, 'fee_percent' => 15, 'max_delay_days' => 15],
            ['article_id' => 18, 'fee_percent' => 30, 'max_delay_days' => 30],
            ['article_id' => 19, 'fee_percent' => 0, 'max_delay_days' => 10],
            ['article_id' => 19, 'fee_percent' => 15, 'max_delay_days' => 15],
            ['article_id' => 19, 'fee_percent' => 30, 'max_delay_days' => 30],
            ['article_id' => 37, 'fee_percent' => 0, 'max_delay_days' => 10],
            ['article_id' => 37, 'fee_percent' => 50, 'max_delay_days' => 30],
        ]);
    }
}
